[project]
name = "youtube-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "yt-dlp>=2025.1.15",
    "openai>=1.12.0",
]
